version: 2

updates:
  - package-ecosystem: npm
    directory: '/app'
    schedule:
      interval: monthly
    target-branch: dev

  - package-ecosystem: docker
    directory: '/app'
    schedule:
      interval: monthly
    target-branch: dev
    ignore:
      - dependency-name: node
        update-types: ['version-update:semver-major'] # Stay within major version

  - package-ecosystem: github-actions
    directory: '/' # Check files in .github/workflows
    schedule:
      interval: monthly
    target-branch: dev

  - package-ecosystem: terraform
    directory: '/iac/modules/app'
    schedule:
      interval: monthly
    target-branch: dev

  - package-ecosystem: terraform
    directory: '/iac/modules/setup'
    schedule:
      interval: monthly
    target-branch: dev

# For each of these, requesting reviews from yourself makes Dependabot PRs easier to find (https://github.com/pulls/review-requested)
#    reviewers:
#      - "YourGitHubUsername"
